name: Bug report
description: Report a bug or issue with this plugin
labels: ["bug"]
assignees:
  - ybw0014
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome to the SlimefunGuguProject issue tracker
        You are reporting a bug in the Chinese-localized version of AlchimiaVitae.
        For feedback and suggestions, please join our QQ group: [QQ group](https://ybw0014.net/go/sf-qgroup).
        Please consider reading [this guide](https://slimefun-wiki.guizhanss.cn/How-to-report-bugs) on how to report bugs effectively.

        <strong><i>You must fill in all fields marked with an asterisk (*)</i></strong>

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before reporting
      options:
        - label: You are using the version downloaded from the build server
          required: true
        - label: You have verified the checksum of the downloaded files
          required: false
        - label: You have not modified the downloaded files
          required: true
        - label: You have searched the [known issues list](https://github.com/SlimefunGuguProject/AlchimiaVitae/issues) and did not find a matching issue
          required: true

  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Describe the problem you are reporting in detail.
        Providing detailed information helps us resolve the issue faster.
      placeholder: Saying only "doesn't work" won't help developers locate the problem.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: |
        Describe how to reproduce the issue step by step.
        If you have a video, please provide a link.
      placeholder: |
        1. xxx
        2. xxx
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        What do you expect to happen?
        Sometimes the issue arises from misunderstanding a feature.
    validations:
      required: true

  - type: input
    id: server-log
    attributes:
      label: Server logs
      description: |
        Check your server logs for errors. If present, upload them to [https://paste.guizhanss.net/](https://paste.guizhanss.net/) and paste the link here.
        **Do not paste logs directly into this field**
      placeholder: https://paste.guizhanss.net/...
    validations:
      required: false

  - type: input
    id: error-report
    attributes:
      label: Error report
      description: |
        If your server log references files in `/plugins/Slimefun/error-reports` (error reports), upload them to [https://paste.guizhanss.net/](https://paste.guizhanss.net/) and paste the link here.
        **Do not paste error reports directly into this field**
      placeholder: https://paste.guizhanss.net/...
    validations:
      required: false

  - type: dropdown
    id: server-software
    attributes:
      label: Server software
      description: Please select the server software you are using
      options:
        - Spigot
        - Paper
        - Purpur
        - Airplane
        - Other (please specify in the issue description)
    validations:
      required: true

  - type: input
    id: minecraft-version
    attributes:
      label: Minecraft version
      description: Please enter your Minecraft version
    validations:
      required: true

  - type: textarea
    id: slimefun-version
    attributes:
      label: Slimefun version
      description: |
        Please enter the Slimefun version you are using
        (e.g. v4.9-canary-08120db)
        If you have admin access, consider running `/sf versions`, screenshotting it, and attaching the full output here.
    validations:
      required: true

  - type: input
    id: version-plugin
    attributes:
      label: Plugin version
      description: |
        Please enter the plugin version
        (e.g. Build 1 (git x114514))
    validations:
      required: true
